spring:
  datasource:
    mysql:
      jdbcUrl: jdbc:mysql://localhost:3306/reusai?useSSL=false&serverTimezone=UTC
      username: root
      password: 00D42s@l
      driver-class-name: com.mysql.cj.jdbc.Driver

    postgresql:
      jdbcUrl: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.rnsyrzyzguctpqmiquom&password=Reusai@2026
      username: rnsyrzyzguctpqmiquom
      password: Reusai@2026
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

supabase:
  url: https://rnsyrzyzguctpqmiquom.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuc3lyenl6Z3VjdHBxbWlxdW9tIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Njk4MTUyOCwiZXhwIjoyMDkyNTU3NTI4fQ.6w5tFfH_a7JhCr5d3KgiIVZy15-YkwqJ5jWTHFEv__A
  bucket: images
