spring:
  datasource:
    mysql:
      jdbcUrl: jdbc:mysql://localhost:3306/reusai?useSSL=false&serverTimezone=UTC
      username: root
      password: 00D42s@l
      driver-class-name: com.mysql.cj.jdbc.Driver

    postgresql:
      jdbcUrl: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.rnsyrzyzguctpqmiquom&password=Reusai@2026
      username: rnsyrzyzguctpqmiquom
      password: Reusai@2026
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false